// <auto-generated />
using System;
using MarketPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703085505_AddCollectedMarketItems")]
    partial class AddCollectedMarketItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketPulse.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Idea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AnalysisRequests");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("MarketScore")
                        .HasColumnType("integer");

                    b.Property<string>("Opportunities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId")
                        .IsUnique();

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.CollectedMarketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permalink")
                        .HasColumnType("text");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SearchQueryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchQueryId");

                    b.HasIndex("AnalysisRequestId", "Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("CollectedMarketItems");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.RedditPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RedditPostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SearchQueryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelfText")
                        .HasColumnType("text");

                    b.Property<string>("Subreddit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchQueryId");

                    b.HasIndex("AnalysisRequestId", "RedditPostId")
                        .IsUnique();

                    b.ToTable("RedditPosts");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.SearchQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRequestId");

                    b.ToTable("SearchQueries");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.AnalysisRequest", "Request")
                        .WithOne("Result")
                        .HasForeignKey("MarketPulse.Domain.Entities.AnalysisResult", "AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.CollectedMarketItem", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.AnalysisRequest", "Request")
                        .WithMany("CollectedMarketItems")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPulse.Domain.Entities.SearchQuery", "SearchQuery")
                        .WithMany()
                        .HasForeignKey("SearchQueryId");

                    b.Navigation("Request");

                    b.Navigation("SearchQuery");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.RedditPost", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.AnalysisRequest", "Request")
                        .WithMany("RedditPosts")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketPulse.Domain.Entities.SearchQuery", "SearchQuery")
                        .WithMany()
                        .HasForeignKey("SearchQueryId");

                    b.Navigation("Request");

                    b.Navigation("SearchQuery");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.SearchQuery", b =>
                {
                    b.HasOne("MarketPulse.Domain.Entities.AnalysisRequest", "Request")
                        .WithMany("SearchQueries")
                        .HasForeignKey("AnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("MarketPulse.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Navigation("CollectedMarketItems");

                    b.Navigation("RedditPosts");

                    b.Navigation("Result");

                    b.Navigation("SearchQueries");
                });
#pragma warning restore 612, 618
        }
    }
}
